### ISSUE TITLE
meta: user feedback

### ISSUE THREAD

**Issue by GaelCondeLosada** [uniconnect-epfl/uniconnect#144]
## To do:
- [x] Make section tabs easier to press on.
- [ ] Make all missing settings screens in figma.
- [x] Improve the password: make an option to hide the password with "****" in registration and finish all checks (some of the checks like password strength are not functional I don't remember which ones).
- [x] After adding a description, the fact that there is still a button “Add a description” made users feel weird. Change the button to “Modify description” or remove it after the user has put their description. 
- [x] On login the button "Continue with google" should have a capital G.
- [x] In registration, “Please check your data” is not a good error message, it doesn’t tell the user what’s wrong. 
- [ ] In a person's profile add a field for authorizations to publish annoucements for a given university. Make a way for us to update these authorizations.
- [ ] Make graph functionality to display some L2 friends depending on the number of common friends and the number of common interests (+ randomness ?).
- [ ] Make graph functionality to display all L2 friends for a given friend only when the L1 friend is selected.
- [x] Make the screen to view all the annoucements in a list.
- [ ] Add annoucements in the database.
- [ ] Refine add annoucement/event screen + implement tags
- [ ] Make interests tab in profile.
- [ ] Make events tab in profile.
- [ ] We need a way to send messages/friend invites, add that to the database and an interface for the "Message" screen to use.
- [ ] Make a screen and database interactions to modify the informations of an event (some user might need it) but that's not a priority.

## To discuss:
- [ ] When opening the datepicker on registration start with a date ~20 years ago ?
- [ ] People are not reading "UC" when reading the logo, do we do something about that ?
- [x] Do we need a dedicated screen to see all infos about an annoucement ?
- [ ] Add a "language", "about", "notifications" and help settings screen ? How are them ? What are their use ?
- [ ] At the beginning we talked about interests but also qualifications. Do we do them ? Do we forget about them ?
- [ ] For events and L2/L3 friends do we display them plain or do we recommend them with an algorithm ? What algorithm ?
