### ISSUE TITLE
meta: figma tasks

### ISSUE THREAD

**Issue by Fyuryy** [uniconnect-epfl/uniconnect#161]
- [x] Add the "back arrow" on all the screens that need it.
- [x] Change the tabs name to more user friendly ones so they are not surprised when arriving on the scan camera or the events (and reorder them if necessary).
- [ ] Add a QR code for events somewhere that users can scan to be redirected to the event page.
(- [ ] Add a screen in which you can see friend invites/messages and send messages.) -> later
(- [ ] Add an "account center" screen to which we can go from the settings (discuss the details with Aidas if necessary).) -> later
- [x] Add a "register to event button" on the event page
