### ISSUE TITLE
meta: tasks for M1

### ISSUE THREAD

**Issue by Aidasvenc** [uniconnect-epfl/uniconnect#29]
- [x] #57

SonarCloud and testing
- [x] #40
- [x] #39
- [x] #41

Additional Lint rules
- [x] #42
- [x] #43

Typescript issues
- [x] navigation type with `as never`
- [x] navigation prop types in `RegistrationStacknavigator`

Naming issues
- [x] rename the graph components and refactor them into components folder
- [x] clean the naming conventions for the files already created

#23 
- [x] custom props for `LowBar` component and navigation actions according to the screen you are at.
- [x] Clean the stack after login and after a successful registration.

#26 
- [x] Implement the real login and registration logic in the screens created in #21 
- [x] #53

#24 
- [x] Resolve the requested changes in the review
- [x] Add a `debouncer` hook for searching in a search bar.

DevOps
- [x] #58
- [x] #59
- [x] #60
- [x] Consider creating a [release branch](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) called "M1" so that you have a clean snapshot of all code and assets related to M1.

SCRUM tasks
- [x] #47
- [x] #48

Individual
- [x] An individual Retrospective for each Sprint
- [x] The PRs you created and were merged (≥2 by M1)
- [x] The PRs you reviewed (≥2 by M1)

Figma and mockups
- [x] #45
- [x] #46
 
New features
- [x] #54
- [ ] Profile page - editing interests
- [ ] Events page - listing all events in a feed

Android compatibility
- [x] #44
